image: maven:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn clean install

deploy:
  stage: deploy
  script:
    - scp target/my-application.jar user@remote-server:/path/to/deploy
    - ssh user@remote-server "sudo systemctl restart my-application"
  only:
    - master
