package com.example.demo.DTO;


public enum UserDesignation {
    MILL_OWNER, MILL_CLERK, COMPANY_AGENT, COMPANY_GATEKEEPER, COMPANY_FINANCING_TEAM, TRANSPORTER_OWNER,
    TRANSPORTER_DRIVER, TRANSPORTER_CLEANER, DOZER_DRIVER, DOZER_CLEANER, TRUCK_DRIVER, TRUCK_CLEANER
}
